name: Sony Stock Checker

on:
  schedule:
    # 5분마다 실행 (UTC 기준이므로 한국 시간과는 차이가 있음)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동으로 실행해볼 수 있는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium requests

    - name: Check Stock
      env:
        TELEGRAM_TOKEN: '7831052389:AAEVBqfJRnvoxLH9R9VNt7_l6eiaRZcWuJQ'
        TELEGRAM_CHAT_ID: '7639681219'
      run: python check_stock.py
