name: Sony Stock Checker

on:
  schedule:
    # 1. 정각에 실행: UTC 0시(오전9시), 9시(오후6시), 12시(오후9시)
    - cron: '0 0,9,12 * * *'
    # 2. 30분에 실행: UTC 2시 30분(오전11시 30분)
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run:
        pip install selenium requests

    - name: Check Stock
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python check_stock.py
